apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: azii1/voteapp-app:latest
        ports:
        - containerPort: 80
       

